# For use with the Rest Client VSCode extension (humao.rest-client)

@baseUrl=http://127.0.0.1:5000

@trueUrl=https://p2-svahnkon.rahtiapp.fi/

@AUTH = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzM3NTYwZWExZWI4NWQ0YTkwZGYxODIiLCJlbWFpbCI6ImhvcnNlLnJlYWxtYW5AVi5vcnNlIiwiaWF0IjoxNjY1OTE3MDcxLCJleHAiOjE2NjYwMDM0NzF9.2smsBoDMrKvOnRZ3a2OImydtjNGBNOmitkBwFgmwaBw

###
GET {{trueUrl}}/cabins
Authorization: Bearer {{AUTH}}

###
GET {{baseUrl}}/orders
###

POST {{baseUrl}}/orders
Content-Type: application/json

{ 
    "service": "Test value",
    "cottage": "cottage",
    "duration": 60
}

###
PATCH {{baseUrl}}/orders/2
Content-Type: application/json

{ 
    "service": "cleaning",
    "cottage": "building",
    "duration": 2
}

###
DELETE {{baseUrl}}/orders/3

###
GET {{baseUrl}}/services
###
POST {{baseUrl}}/services
Content-Type: application/json

{ 
    "name": "Test value",
    "cottage": "cottage",
    "hourly_cost": 50
}

###
PATCH {{baseUrl}}/services/7
Content-Type: application/json

{ 
    "name": "value 2",
    "cottage": "house",
    "hourly_cost": 100
}

###
DELETE {{baseUrl}}/services/10
