# For use with the Rest Client VSCode extension (humao.rest-client)

@baseUrl=http://127.0.0.1:5000

@trueUrl=https://p2-svahnkon.rahtiapp.fi/

@AUTH = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzM3NTYwZWExZWI4NWQ0YTkwZGYxODIiLCJlbWFpbCI6ImhvcnNlLnJlYWxtYW5AVi5vcnNlIiwiaWF0IjoxNjY1OTE3MDcxLCJleHAiOjE2NjYwMDM0NzF9.2smsBoDMrKvOnRZ3a2OImydtjNGBNOmitkBwFgmwaBw

###
GET {{trueUrl}}/cabins
Authorization: Bearer {{AUTH}}

###
GET {{trueUrl}}/orders
###

POST {{trueUrl}}/orders
Content-Type: application/json

{ 
    "service": "12",
    "cottage": "633762f8d22189b950cf23db",
    "duration": 80
}

###
PATCH {{trueUrl}}/orders/6
Content-Type: application/json

{ 
    "service": "7",
    "cottage": "633887595c971c520456d6c6",
    "duration": 1665668640000
}

###
DELETE {{trueUrl}}/orders/5

###
GET {{trueUrl}}/services
###
POST {{trueUrl}}/services
Content-Type: application/json

{ 
    "name": "clean cottage",
    "cottage": "633762f8d22189b950cf23db",
    "hourly_cost": 10
}

###
PATCH {{trueUrl}}/services/1
Content-Type: application/json

{ 
    "name": "clean cottage",
    "cottage": "633887595c971c520456d6c6",
    "hourly_cost": 10
}

###
DELETE {{trueUrl}}/services/10
