# For use with the Rest Client VSCode extension (humao.rest-client)

@baseUrl=http://127.0.0.1:5000

@trueURL=https://p2-svahnkon.rahtiapp.fi/

###
GET {{baseUrl}}/orders
###
POST {{baseUrl}}/orders
Content-Type: application/json

{ 
    "service": "Test value",
    "cottage": "cottage",
    "duration": 60
}
###
GET {{baseUrl}}/services
###
POST {{baseUrl}}/services
Content-Type: application/json

{ 
    "name": "Test value",
    "cottage": "cottage",
    "hourly_cost": 50
}
